name: CICD for Deploy

on:
  workflow_dispatch:

env:
  ARTIFACT_NAME: CICD_DEMO


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./target/*.jar

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: code-demo-0.0.1-SNAPSHOT.jar
          remote: /home/cicd/application.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          rmRemote: true

      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: nohup java -jar /home/cicd/application.jar  > /home/cicd/logs/application.log &
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.PASSWORD }}
          args: "-tt"

    needs: build
