name: CICD for Deploy

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: modify file name
        run: mv target/*.jar application.jar

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          source: "application.jar"
          target: /home/cicd/

      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: nohup java -jar /home/cicd/application.jar  > /home/cicd/logs/application.log &
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.PASSWORD }}
          args: "-tt"

    needs: build
